import { useState } from 'react';
import { Sparkles, Loader2, Music, Send, Wand2, Download, ExternalLink, Copy, Check } from 'lucide-react';
import { getTopArtists, getTopTracks } from '../services/lastfm';
import { getApiBaseUrl } from '../config/api';

const PROMPT_EXAMPLES = [
  "Create a chill Sunday morning playlist",
  "Make me a workout playlist with high energy",
  "Songs for coding at 3am",
  "Road trip vibes for a long drive",
  "Rainy day mood playlist",
  "Party playlist for Friday night",
  "Focus music for studying",
  "Romantic dinner playlist",
];

const PlaylistGenerator = ({ username }) => {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [playlist, setPlaylist] = useState(null);
  const [copied, setCopied] = useState(false);

  const generatePlaylist = async () => {
    if (!prompt.trim()) return;

    setLoading(true);
    try {
      // Fetch user's music data for context
      const [topArtistsData, topTracksData] = await Promise.all([
        getTopArtists(username, '1month', 50),
        getTopTracks(username, '1month', 50),
      ]);

      const topArtists = topArtistsData?.artist || [];
      const topTracks = topTracksData?.track || [];

      // Prepare context for AI
      const userContext = {
        topArtists: topArtists.slice(0, 20).map(a => a.name),
        topTracks: topTracks.slice(0, 20).map(t => ({
          name: t.name,
          artist: t.artist?.name || t.artist?.['#text'] || ''
        })),
        prompt: prompt,
      };

      const response = await fetch(`${getApiBaseUrl()}/api/playlist/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(userContext)
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data?.error || `Playlist generation failed (${response.status})`);
      }

      if (!data?.success || !data?.playlist) {
        throw new Error(data?.error || 'Failed to generate playlist');
      }

      setPlaylist({
        ...data.playlist,
        generatedAt: new Date().toISOString(),
        prompt: prompt,
      });

    } catch (error) {
      console.error('Error generating playlist:', error);
      alert('Failed to generate playlist. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    if (!playlist) return;
    
    const text = `${playlist.title}\n\n${playlist.tracks.map((t, i) => 
      `${i + 1}. ${t.title} - ${t.artist}`
    ).join('\n')}`;
    
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const exportForSpotify = () => {
    if (!playlist) return;
    
    const spotifyGuide = `🎵 ${playlist.title}
${playlist.description}

📋 TRACKS TO ADD TO SPOTIFY:
${playlist.tracks.map((t, i) => `${i + 1}. ${t.artist} - ${t.title}`).join('\n')}

💡 HOW TO CREATE THIS PLAYLIST IN SPOTIFY:

Option 1 - Manual (Recommended):
1. Open Spotify and create a new playlist
2. Search for each track above and add it to your playlist

Option 2 - Use Spotlistr.com:
1. Go to https://www.spotlistr.com/
2. Choose "By Textbox"
3. Paste the track list above
4. Click "Create Playlist"
5. Sign in to Spotify and it will create the playlist for you!

Option 3 - Use Playlist Converter:
1. Go to https://www.playlist-converter.net/
2. Choose "Text" as source
3. Paste the track list
4. Choose Spotify as destination
5. Sign in and convert

🎧 Generated by AI Playlist Generator
`;
    
    const blob = new Blob([spotifyGuide], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${playlist.title.replace(/[^a-z0-9]/gi, '_')}_spotify_import.txt`;
    a.click();
    
    alert('Export successful! The file contains your playlist and instructions for importing to Spotify.');
  };

  const openSpotifySearch = (track) => {
    const query = encodeURIComponent(`${track.title} ${track.artist}`);
    window.open(`https://open.spotify.com/search/${query}`, '_blank');
  };

  const getSpotifySearchUrl = (track) => {
    const query = encodeURIComponent(`${track.title} ${track.artist}`);
    return `https://open.spotify.com/search/${query}`;
  };

  const getYouTubeSearchUrl = (track) => {
    const query = encodeURIComponent(`${track.title} ${track.artist}`);
    return `https://www.youtube.com/results?search_query=${query}`;
  };

  return (
    <div className="min-h-screen p-8" style={{ background: 'transparent' }}>
      <div className="mx-auto max-w-5xl">
        {/* Header */}
        <header className="mb-8">
          <div className="mb-4 flex items-center gap-3">
            <div className="rounded-full bg-[#6B5A2A]/10 p-3">
              <Sparkles className="h-8 w-8 text-[#6B5A2A]" />
            </div>
            <div>
              <h1 className="font-['Amiri_Quran'] text-7xl font-normal text-[#3E3D1A] md:text-8xl">
                AI Playlist Generator
              </h1>
              <p className="mt-2 font-['Inter_Display'] text-lg font-light text-[#2D2D2D] md:text-xl">
                Describe your perfect playlist and let AI create it
              </p>
            </div>
          </div>
        </header>

        {/* Input Section */}
        <div className="mb-8 rounded-[30px] bg-white/70 p-6 shadow-lg backdrop-blur-sm ring-1 ring-[#CFD0B9]/30">
          <label className="mb-3 block font-['Inter'] text-sm font-semibold text-[#3E3D1A]/70">
            Describe your playlist
          </label>
          
          <div className="mb-4 flex gap-3">
            <input
              type="text"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && generatePlaylist()}
              placeholder="e.g., Create a chill Sunday morning playlist..."
              className="flex-1 rounded-[25px] border-2 border-[#CFD0B9] bg-white px-6 py-4 font-['Inter'] text-base text-[#3E3D1A] transition-all placeholder:text-[#6B5A2A]/40 focus:border-[#6B5A2A] focus:outline-none focus:ring-2 focus:ring-[#6B5A2A]/20"
            />
            <button
              onClick={generatePlaylist}
              disabled={loading || !prompt.trim()}
              className="flex items-center gap-2 rounded-[25px] bg-[#6B5A2A] px-8 py-4 font-['Inter'] text-base font-semibold text-white shadow-md transition-all hover:bg-[#55491A] disabled:bg-[#CFD0B9] disabled:text-[#6B5A2A]/50"
            >
              {loading ? (
                <>
                  <Loader2 className="h-5 w-5 animate-spin" />
                  <span>Creating...</span>
                </>
              ) : (
                <>
                  <Wand2 className="h-5 w-5" />
                  <span>Generate</span>
                </>
              )}
            </button>
          </div>

          {/* Example Prompts */}
          <div>
            <p className="mb-3 font-['Inter'] text-xs font-semibold uppercase tracking-wider text-[#3E3D1A]/70">
              Try these prompts:
            </p>
            <div className="flex flex-wrap gap-2">
              {PROMPT_EXAMPLES.map((example) => (
                <button
                  key={example}
                  onClick={() => setPrompt(example)}
                  className="rounded-full bg-[#EECEA4]/30 px-4 py-2 font-['Inter'] text-xs text-[#3E3D1A] transition-all hover:bg-[#EECEA4]/50"
                >
                  {example}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Loading State */}
        {loading && (
          <div className="rounded-[30px] bg-white/70 p-12 text-center shadow-lg backdrop-blur-sm ring-1 ring-[#CFD0B9]/30">
            <Loader2 className="mx-auto mb-4 h-12 w-12 animate-spin text-[#6B5A2A]" />
            <p className="font-['Inter'] text-lg text-[#3E3D1A]">
              AI is curating your perfect playlist...
            </p>
            <p className="mt-2 font-['Inter'] text-sm text-[#6B5A2A]">
              Analyzing your taste and finding the best tracks
            </p>
          </div>
        )}

        {/* Playlist Result */}
        {playlist && !loading && (
          <div className="space-y-6">
            {/* Playlist Header */}
            <div className="rounded-[30px] bg-gradient-to-br from-[#6B5A2A] to-[#55491A] p-8 shadow-xl">
              <div className="mb-4 flex items-start justify-between">
                <div className="flex-1">
                  <h2 className="mb-2 font-['Amiri_Quran'] text-4xl font-normal text-white">
                    {playlist.title}
                  </h2>
                  <p className="mb-4 font-['Inter'] text-lg text-white/90">
                    {playlist.description}
                  </p>
                  <div className="rounded-[20px] bg-white/10 p-4 backdrop-blur-sm">
                    <p className="font-['Inter'] text-sm font-semibold text-white/70">
                      AI's Reasoning:
                    </p>
                    <p className="mt-1 font-['Inter'] text-base text-white">
                      {playlist.reasoning}
                    </p>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex flex-wrap gap-3">
                <button
                  onClick={exportForSpotify}
                  className="flex items-center gap-2 rounded-[20px] bg-green-600 px-6 py-3 font-['Inter'] text-base font-semibold text-white backdrop-blur-sm transition-all hover:bg-green-700"
                >
                  <Download className="h-5 w-5" />
                  Export for Spotify
                </button>
                <button
                  onClick={copyToClipboard}
                  className="flex items-center gap-2 rounded-[20px] bg-white/20 px-5 py-2.5 font-['Inter'] text-sm font-medium text-white backdrop-blur-sm transition-all hover:bg-white/30"
                >
                  {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  {copied ? 'Copied!' : 'Copy List'}
                </button>
              </div>
            </div>

            {/* Track List */}
            <div className="rounded-[30px] bg-white/70 p-6 shadow-lg backdrop-blur-sm ring-1 ring-[#CFD0B9]/30">
              <h3 className="mb-5 font-['Amiri_Quran'] text-2xl font-normal text-[#3E3D1A]">
                {playlist.tracks.length} Tracks
              </h3>
              <div className="space-y-3">
                {playlist.tracks.map((track, index) => (
                  <div
                    key={`${track.title}-${track.artist}-${index}`}
                    className="rounded-[20px] bg-gradient-to-r from-[#EECEA4]/20 to-[#FFE5D9]/20 p-5 ring-1 ring-[#CFD0B9]/30 transition-all hover:from-[#EECEA4]/40 hover:to-[#FFE5D9]/40"
                  >
                    <div className="mb-3 flex items-start justify-between gap-4">
                      <div className="flex-1">
                        <div className="mb-1 flex items-center gap-3">
                          <span className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#6B5A2A] font-['Inter'] text-sm font-bold text-white">
                            {index + 1}
                          </span>
                          <div>
                            <p className="font-['Inter'] text-lg font-semibold text-[#3E3D1A]">
                              {track.title}
                            </p>
                            <p className="font-['Inter'] text-sm text-[#6B5A2A]">
                              {track.artist}
                            </p>
                          </div>
                        </div>
                        <p className="ml-11 font-['Inter'] text-sm italic text-[#6B5A2A]/80">
                          "{track.why}"
                        </p>
                      </div>
                      <div className="flex flex-shrink-0 gap-2">
                        <button
                          onClick={() => openSpotifySearch(track)}
                          className="flex items-center gap-1.5 rounded-full bg-green-600 px-3 py-1.5 font-['Inter'] text-xs font-medium text-white transition-all hover:bg-green-700"
                        >
                          Spotify
                          <ExternalLink className="h-3 w-3" />
                        </button>
                        <a
                          href={getYouTubeSearchUrl(track)}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center gap-1.5 rounded-full bg-red-600 px-3 py-1.5 font-['Inter'] text-xs font-medium text-white transition-all hover:bg-red-700"
                        >
                          YouTube
                          <ExternalLink className="h-3 w-3" />
                        </a>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Generate Another */}
            <div className="text-center">
              <button
                onClick={() => {
                  setPlaylist(null);
                  setPrompt('');
                }}
                className="rounded-[25px] bg-[#EECEA4] px-8 py-4 font-['Inter'] text-base font-semibold text-[#3E3D1A] shadow-md transition-all hover:bg-[#6B5A2A] hover:text-white"
              >
                Generate Another Playlist
              </button>
            </div>
          </div>
        )}

        {/* Empty State */}
        {!playlist && !loading && (
          <div className="rounded-[30px] bg-white/70 p-12 text-center shadow-lg backdrop-blur-sm ring-1 ring-[#CFD0B9]/30">
            <div className="mx-auto mb-6 flex h-24 w-24 items-center justify-center rounded-full bg-[#6B5A2A]/10">
              <Music className="h-12 w-12 text-[#6B5A2A]" />
            </div>
            <h3 className="mb-3 font-['Amiri_Quran'] text-3xl font-normal text-[#3E3D1A]">
              Ready to Create Your Playlist
            </h3>
            <p className="font-['Inter'] text-base text-[#6B5A2A]">
              Describe the perfect playlist and our AI will curate it based on your music taste
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default PlaylistGenerator;
